version: 2
jobs:
  build:
    docker:
      - image: z0li/hugo-builder:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ef:75:81:ff:48:0d:8f:ff:5f:fb:0c:72:df:6d:f6:d4"
      - checkout
      - run: git submodule update --init
      - run: hugo -v -s /src -d /src/public
      - run:
          name: test the generated html files
          command: htmlproofer /src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - deploy:
          name: push to master branch
          command: sh deploy.sh